const apiUrl = process.env.REACT_APP_API_URL;

const mockUserList = [
  {
    _id: 8801,
    username: "user01",
    role: "admin",
    email: "user01@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529001",
  },
  {
    _id: 8802,
    username: "sg-user02",
    role: "admin",
    email: "user02@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529002",
  },
  {
    _id: 8803,
    username: "user03",
    role: "user",
    email: "user03@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529003",
  },
  {
    _id: 8804,
    username: "sg-user04",
    role: "user",
    email: "user04@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529004",
  },
  {
    _id: 8805,
    username: "user05",
    role: "user",
    email: "user05@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529005",
  },
  {
    _id: 8806,
    username: "sg-user06",
    role: "user",
    email: "user06@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529006",
  },
  {
    _id: 8807,
    username: "user07",
    role: "user",
    email: "user07@gmail.com",
    image: "https://pbs.twimg.com/media/FJ5Ns33XEAYUG1N.jpg",
    phone_number: "082385529007",
  },
];

const mockAgentList = [
  {
    _id: 8801,
    name: "sg-agent01",
    email: "agent01@gmail.com",
    image: `${apiUrl}/public/uploads/agent02.png`,
    phone_number: "082385529001",
    country: "Indonesia",
    city: "Jakarta",
  },
  {
    _id: 8802,
    name: "agent02",
    email: "agent02@gmail.com",
    image: `${apiUrl}/public/uploads/agent06.jpg`,
    phone_number: "082385529002",
    country: "Indonesia",
    city: "Jakarta",
  },
  {
    _id: 8803,
    name: "sg-agent03",
    email: "agent03@gmail.com",
    image: `${apiUrl}/public/uploads/agent02.png`,
    phone_number: "082385529003",
    country: "Indonesia",
    city: "Jakarta",
  },
  {
    _id: 8804,
    name: "agent04",
    email: "agent04@gmail.com",
    image: `${apiUrl}/public/uploads/agent06.jpg`,
    phone_number: "082385529004",
    country: "Indonesia",
    city: "Jakarta",
  },
  {
    _id: 8805,
    name: "sg-agent05",
    email: "agent05@gmail.com",
    image: `${apiUrl}/public/uploads/agent02.png`,
    phone_number: "082385529005",
    country: "Indonesia",
    city: "Jakarta",
  },
  {
    _id: 8806,
    name: "agent06",
    email: "agent06@gmail.com",
    image: `${apiUrl}/public/uploads/agent06.jpg`,
    phone_number: "082385529006",
    country: "Indonesia",
    city: "Jakarta",
  },
  {
    _id: "60bca4fd033e1d38148d6703",
    name: "fred+agent+2",
    email: "fred+agent+2@gmail.com",
    image: `${apiUrl}/public/uploads/agent02.jpg`,
    phone_number: "082385529008",
    country: "indonesia",
    city: "tanjung pinang",
  },
];

const mockFeaturedListingList = [
  {
    _id: "60f434d6fbba829a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    image_thumbnail: `${apiUrl}/public/uploads/villa-aston01.webp`,
    type: "apartment",
    price: "1.000.000",
    is_featured: true,
    is_renting: false,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment data.",
    status: "available",
    country: "indonesia",
    city: "batam",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "sg-featured-listing01",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "sg-agent01",
      email: "fred+agent+208@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba829a87ff3ffb",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    image_thumbnail: `${apiUrl}/public/uploads/apart88-01.webp`,
    type: "apartment",
    price: "1.000.000",
    is_featured: true,
    is_renting: false,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment data.",
    status: "available",
    country: "indonesia",
    city: "jakarta",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "featured-listing02",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "agent08",
      email: "fred+agent+212@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba829a87ff3ffc",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    image_thumbnail: `${apiUrl}/public/uploads/villa-aston01.webp`,
    type: "apartment",
    price: "1.000.000",
    is_featured: true,
    is_renting: false,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment data.",
    status: "available",
    country: "indonesia",
    city: "batam",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "sg-featured-listing03",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "sg-agent03",
      email: "fred+agent+2123@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba829a87ff3ffd",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    image_thumbnail: `${apiUrl}/public/uploads/apart88-01.webp`,
    type: "apartment",
    price: "1.000.000",
    is_featured: true,
    is_renting: false,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment data.",
    status: "available",
    country: "indonesia",
    city: "jakarta",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "featured-listing04",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "agent052",
      email: "fred+agent+22@gmail.com",
      phone_number: "082385529008",
    },
  },
];

const mockListingList = [
  {
    _id: "60f434d6fbba829a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    type: "apartment",
    price: "1.000.000",
    is_featured: true,
    is_renting: false,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment data.",
    status: "available",
    country: "indonesia",
    city: "batam",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "Apartment 01",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "fred+agent+2",
      email: "fred+agent+2@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba002a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/villa-aston01.webp`,
      `${apiUrl}/public/uploads/apart88-01.webp`,
    ],
    type: "apartment",
    price: "880.000",
    is_featured: false,
    is_renting: true,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment 2 data.",
    status: "available",
    country: "indonesia",
    city: "batam",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "Apartment 02",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "fred+agent+2",
      email: "fred+agent+2@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba293a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    type: "house",
    price: "3.250.000",
    is_featured: true,
    is_renting: false,
    bedroom_count: 5,
    bathroom_count: 3,
    building_size: 88,
    description: "this is the description of the house data.",
    status: "available",
    country: "malaysia",
    city: "kuala lumpur",
    address: "kuala lumpur street B2 81, malaysia entertainment district",
    name: "House 01",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent06.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "fred+agent+2",
      email: "fred+agent+2@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba828a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    type: "apartment",
    price: "1.000.000",
    is_featured: false,
    is_renting: true,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment data.",
    status: "available",
    country: "indonesia",
    city: "batam",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "Apartment 01",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "fred+agent+2",
      email: "fred+agent+2@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba008a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/villa-aston01.webp`,
      `${apiUrl}/public/uploads/apart88-01.webp`,
    ],
    type: "apartment",
    price: "880.000",
    is_featured: false,
    is_renting: true,
    bedroom_count: 3,
    bathroom_count: 2,
    building_size: 54,
    description: "this is the description of the apartment 2 data.",
    status: "available",
    country: "indonesia",
    city: "batam",
    address: "Kecamatan Batam Kota, Komplek Kintamani Blok B no 8",
    name: "Apartment 02",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent02.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "fred+agent+2",
      email: "fred+agent+2@gmail.com",
      phone_number: "082385529008",
    },
  },
  {
    _id: "60f434d6fbba298a87ff3ffa",
    images: [
      `${apiUrl}/public/uploads/apart88-01.webp`,
      `${apiUrl}/public/uploads/villa-aston01.webp`,
    ],
    type: "house",
    price: "3.250.000",
    is_featured: false,
    is_renting: true,
    bedroom_count: 5,
    bathroom_count: 3,
    building_size: 88,
    description: "this is the description of the house data.",
    status: "available",
    country: "malaysia",
    city: "kuala lumpur",
    address: "kuala lumpur street B2 81, malaysia entertainment district",
    name: "House 01",
    agent: {
      _id: "60bca4fd033e1d38148d6703",
      image: `${apiUrl}/public/uploads/agent06.jpg`,
      country: "indonesia",
      city: "tanjung pinang",
      name: "fred+agent+2",
      email: "fred+agent+2@gmail.com",
      phone_number: "082385529008",
    },
  },
];

export {
  mockUserList,
  mockAgentList,
  mockFeaturedListingList,
  mockListingList,
};
